import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import path from 'node:path'

import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

// HACK(penumbra-migration): the bankD demo wasm build compiles out
// transaction_perspective_and_view, so the browser can't decrypt private txs.
// Until the fork-native wallet lands, decryption runs server-side through
// tools/shieldd-note-reader (Go) using dev-wallet IVKs. Build the binary with:
//   go build -C tools/shieldd-note-reader -o ../../.dist/shieldd-note-reader .

export const dynamic = 'force-dynamic'

// IVKs to try, comma-separated via SHIELDD_DECRYPT_IVKS. Defaults cover the two
// local dev wallets; label is cosmetic.
const DEFAULT_IVKS: Array<{ label: string; ivk: string }> = [
  { label: 'test-wallet', ivk: 'ee22766b1dea2fd2d388681655f8e8794c2ea8e20c3468f71cb0d8f82a817d00' },
  { label: 'acc0', ivk: 'ea11857c1769115b70c543971cdc5846c4ab7bcedeb11f2f99b961ca40394803' },
]
const IVK_HEX = /^[0-9a-fA-F]{64}$/
const B64 = /^[A-Za-z0-9+/=]+$/
// What the reader actually prints, e.g.
//   DECRYPTED action 0 output 0 (transfer): amount=40000000000 asset_id=<hex> recipient=<hex>
// The action index and kind were added to the tool without this being updated,
// so the old `DECRYPTED output N:` pattern silently matched nothing and every
// decrypt came back empty even when the reader had read the note.
const OUTPUT_LINE =
  /^DECRYPTED action (\d+) output (\d+) \(([a-z_]+)\): amount=(\d+) asset_id=([0-9a-f]+) recipient=([0-9a-f]+)$/

// The demo wallets are regenerated by every clean bring-up, so their keys change
// under us. scripts/demo-ivks.sh derives them for whatever stack is up and writes
// them here; read at request time so a reset needs no server restart.
function demoIvks(): Array<{ label: string; ivk: string }> {
  try {
    const file = path.join(process.cwd(), '../..', '.localnet', 'audit-demo', 'ivks.json')
    const parsed = JSON.parse(readFileSync(file, 'utf8')) as Array<{
      label?: string
      ivk?: string
    }>
    return parsed
      .filter((x): x is { label: string; ivk: string } => Boolean(x.ivk && IVK_HEX.test(x.ivk)))
      .map((x) => ({ label: x.label ?? 'demo', ivk: x.ivk }))
  } catch {
    return []
  }
}

function configuredIvks(): Array<{ label: string; ivk: string }> {
  const raw = process.env.SHIELDD_DECRYPT_IVKS
  const env = raw
    ? raw
        .split(',')
        .map((x) => x.trim())
        .filter((x) => IVK_HEX.test(x))
        .map((ivk, i) => ({ label: `env-${i}`, ivk }))
    : []
  const all = [...env, ...demoIvks(), ...DEFAULT_IVKS]
  // first label wins per key, so an explicit env entry keeps its name
  const seen = new Set<string>()
  return all.filter(({ ivk }) => !seen.has(ivk) && seen.add(ivk))
}

function readerPath(): string {
  return process.env.SHIELDD_NOTE_READER ?? path.join(process.cwd(), '../..', '.dist', 'shieldd-note-reader')
}

export async function POST(request: NextRequest) {
  let txBytes: string
  try {
    const body = (await request.json()) as { tx_bytes?: string }
    txBytes = (body.tx_bytes ?? '').trim()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }
  if (!txBytes || !B64.test(txBytes)) {
    return NextResponse.json({ error: 'tx_bytes must be base64' }, { status: 400 })
  }

  const notes: Array<{
    wallet: string
    action: number
    index: number
    kind: string
    amount: string
    asset_id: string
    recipient: string
  }> = []
  for (const { label, ivk } of configuredIvks()) {
    const run = spawnSync(readerPath(), ['--ivk', ivk], { input: txBytes, encoding: 'utf8', timeout: 10_000 })
    if (run.error) {
      return NextResponse.json({ error: `note reader unavailable: ${run.error.message}` }, { status: 500 })
    }
    if (run.status !== 0) {
      return NextResponse.json({ error: `note reader failed: ${run.stderr.trim()}` }, { status: 500 })
    }
    for (const line of run.stdout.split('\n')) {
      const m = OUTPUT_LINE.exec(line.trim())
      if (m) {
        notes.push({
          wallet: label,
          action: Number(m[1]),
          index: Number(m[2]),
          kind: m[3],
          amount: m[4],
          asset_id: m[5],
          recipient: m[6],
        })
      }
    }
  }

  return NextResponse.json({
    decrypted_by: 'server (shieldd-note-reader)',
    notes,
    note: notes.length === 0 ? 'no output notes decrypted with the configured IVKs' : undefined,
  })
}
