packages:
  - admin
  - packages/*
overrides:
  '@mizufinance/bech32m': https://github.com/mizufinance/penumbra-web/releases/download/bankd-demo.1/mizufinance-bech32m-18.0.1-bankd-demo.1.tgz
  '@mizufinance/protobuf': file:admin/vendor/mizufinance-protobuf-11.0.1-bankd-demo.14.tgz
  '@mizufinance/types': https://github.com/mizufinance/penumbra-web/releases/download/bankd-demo.1/mizufinance-types-36.0.1-bankd-demo.1.tgz
  '@mizufinance/wasm': file:admin/vendor/mizufinance-wasm-53.0.1-bankd-commonware.1.tgz
onlyBuiltDependencies:
  - '@cosmology/protobufjs'
  - '@swc/core'
  - esbuild
  - bufferutil
  - utf-8-validate
