version: 2
multi-ecosystem-groups:
  weekly:
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "weekly"
    patterns: ["*"]
  - package-ecosystem: "cargo"
    directory: "/"
    multi-ecosystem-group: "weekly"
    patterns: ["*"]
  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "weekly"
    patterns: ["*"]
