#![allow(clippy::double_must_use)] // Async methods generated by `rpc` add `must_use`.

use alloy_primitives::Bytes;
use jsonrpsee::{core::RpcResult, proc_macros::rpc, types::ErrorObjectOwned};
use serde::Serialize;
use tempo_evm::shield::ShieldHandle;

/// A shieldd state checkpoint on the node's disk.
#[derive(Debug, Clone, Serialize)]
pub struct ShieldCheckpoint {
    /// RocksDB checkpoint dir. The caller owns it and deletes it when done.
    pub path: String,
    /// Finalized shieldd height the checkpoint holds.
    pub height: u64,
}

#[rpc(server, namespace = "bankd")]
pub trait BankdShieldApi {
    /// Snapshots finalized shieldd state to a local dir so a wallet on the same host can
    /// sync and prove against it. Admin only, since it writes to the node's disk.
    #[method(name = "shieldCheckpoint")]
    async fn shield_checkpoint(&self) -> RpcResult<ShieldCheckpoint>;

    /// Read-only protobuf queries; each response is a hex-encoded message.
    #[method(name = "shieldQuery")]
    async fn shield_query(&self, method: String, request: Bytes) -> RpcResult<Vec<Bytes>>;
}

/// `bankd_shield*` RPCs backed by the node's shieldd engine.
#[derive(Debug, Clone)]
pub struct BankdShieldRpc {
    shield: ShieldHandle,
}

impl BankdShieldRpc {
    pub fn new(shield: ShieldHandle) -> Self {
        Self { shield }
    }
}

#[async_trait::async_trait]
impl BankdShieldApiServer for BankdShieldRpc {
    async fn shield_query(&self, method: String, request: Bytes) -> RpcResult<Vec<Bytes>> {
        if request.len() > 1_048_576 {
            return Err(ErrorObjectOwned::owned(
                -32602,
                "Shieldd query request exceeds 1 MiB",
                None::<()>,
            ));
        }
        let shield = self.shield.clone();
        tokio::task::spawn_blocking(move || shield.query(&method, &request))
            .await
            .map_err(|e| internal(e.to_string()))?
            .map_err(internal)
            .map(|messages| messages.into_iter().map(Bytes::from).collect())
    }

    async fn shield_checkpoint(&self) -> RpcResult<ShieldCheckpoint> {
        let shield = self.shield.clone();
        // Takes the executor lock and does disk IO, keep it off the async workers.
        let (path, height) = tokio::task::spawn_blocking(move || shield.checkpoint())
            .await
            .map_err(|e| internal(e.to_string()))?
            .map_err(internal)?;
        Ok(ShieldCheckpoint {
            path: path.display().to_string(),
            height,
        })
    }
}

fn internal(msg: String) -> ErrorObjectOwned {
    ErrorObjectOwned::owned(
        jsonrpsee::types::error::INTERNAL_ERROR_CODE,
        msg,
        None::<()>,
    )
}
