import { createHash } from 'node:crypto'

import { type Address, getAddress, getContractAddress } from 'viem'

import policy from '@/generated/supervisor-indexer-policy.json'
import { chainDefinition } from '@/lib/config'
import { verifyBlockSignature } from '@/lib/supervisor/signature'

const DEFAULT_URLS = ['http://localhost:9181/api/v0/graphql','http://localhost:9183/api/v0/graphql','http://localhost:9184/api/v0/graphql']
const PREFIX_PATTERN = /^[A-Za-z][A-Za-z0-9_]*$/, PAGE_SIZE = 500, MAX_PAGES = 20
export class InventoryUnavailableError extends Error {}
export type DeployedContract = { address: Address; deployer: Address; txHash: string; blockNumber: number }
export type ContractInventory = {
  contracts: DeployedContract[]
  identity: { wallet: Address; chainId: number }
  provenance: { source: 'Shinzo'; signerIds: string[]; requiredSigners: number; latestHeight: number; latestHash: string; latestTime: string; indexedStartHeight: number; rpcAgreement: true; collectionPrefix: string }
  coverage: { complete: boolean; indexedRangeComplete: boolean; truncated: boolean; reason?: string }
  limitations: { topLevelCreate: true; internalCreate: false; create2: false; ownershipNotEstablished: true }
}
type Tx = { hash?: unknown; from?: unknown; to?: unknown; nonce?: unknown; status?: unknown; blockNumber?: unknown }
type Block = { hash?: unknown; number?: unknown; timestamp?: unknown }
type Signature = { blockNumber?: unknown; blockHash?: unknown; merkleRoot?: unknown; signatureIdentity?: unknown; signatureType?: unknown; signatureValue?: unknown }
type Source = { contracts: DeployedContract[]; signerIdentity: string; latestHeight: number; latestHash: string; latestTime: string; indexedStartHeight: number; truncated: boolean; digest: string }
const prefix = () => { const value=process.env.SHINZO_COLLECTION_PREFIX ?? 'Bankd__Brazil'; if(!PREFIX_PATTERN.test(value)) throw new Error('Invalid collection prefix'); return value }
type Endpoint = { url: string; signerIdentity: string; signerId: string }
const endpoints = (): Endpoint[] => {
  const configured = (process.env.SHINZO_GRAPHQL_URLS ?? process.env.SHINZO_GRAPHQL_URL)?.split(',').map(x => x.trim()).filter(Boolean) ?? DEFAULT_URLS
  if (configured.length > policy.indexers.length) throw new Error('More indexer endpoints than registered identities')
  if (process.env.NODE_ENV === 'production' && configured.some((url) => !url.startsWith('https://'))) throw new Error('Production indexer endpoints must use authenticated HTTPS')
  return configured.map((url, index) => ({ url, signerIdentity: policy.indexers[index].identity.toLowerCase(), signerId: policy.indexers[index].id }))
}
function query(p: string, wallet: string, offset: number) { return `query ContractInventory { txs: ${p}__Transaction(filter: {from: {_eq: "${wallet}"}, to: {_eq: ""}, status: {_eq: true}}, order: [{blockNumber: DESC}, {hash: ASC}], limit: ${PAGE_SIZE}, offset: ${offset}) { hash from to nonce status blockNumber } latest: ${p}__Block(order: {number: DESC}, limit: 1) { hash number timestamp } oldest: ${p}__Block(order: {number: ASC}, limit: 1) { hash number timestamp } signatures: ${p}__BlockSignature(order: [{blockNumber: DESC}, {blockHash: ASC}], limit: 1) { blockNumber blockHash merkleRoot signatureIdentity signatureType signatureValue } }` }
const safeHeight=(v:unknown)=>{ const n=typeof v==='number'?v:Number(v); if(!Number.isSafeInteger(n)||n<0) throw new Error('Invalid indexed height'); return n }
function contract(tx: Tx, wallet: Address): DeployedContract | null { try { if(tx.status!==true||tx.to!==''||typeof tx.hash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(tx.hash)||typeof tx.from!=='string'||tx.from.toLowerCase()!==wallet.toLowerCase()||typeof tx.nonce!=='string') return null; const blockNumber=safeHeight(tx.blockNumber); return {address:getContractAddress({from:wallet,nonce:BigInt(tx.nonce)}),deployer:wallet,txHash:tx.hash.toLowerCase(),blockNumber} } catch{return null} }
async function source(endpoint:Endpoint,wallet:Address,p:string):Promise<Source>{ let rows:DeployedContract[]=[]; let latest:Block|undefined,oldest:Block|undefined,sig:Signature|undefined,truncated=false
 for(let page=0;page<MAX_PAGES;page++){ const response=await fetch(endpoint.url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:query(p,wallet,page*PAGE_SIZE)}),cache:'no-store',signal:AbortSignal.timeout(5000)}); if(!response.ok) throw new Error('Indexer unavailable'); const body=await response.json() as {data?:{txs?:Tx[];latest?:Block[];oldest?:Block[];signatures?:Signature[]};errors?:unknown[]}; if(body.errors?.length||!Array.isArray(body.data?.txs)) throw new Error('Invalid index response'); latest??=body.data.latest?.[0]; oldest??=body.data.oldest?.[0]; sig??=body.data.signatures?.[0]; rows.push(...body.data.txs.map(x=>contract(x,wallet)).filter((x):x is DeployedContract=>!!x)); if(body.data.txs.length<PAGE_SIZE) break; if(page===MAX_PAGES-1) truncated=true }
 if(!latest||!oldest||!sig||typeof latest.hash!=='string'||typeof latest.timestamp!=='string'||typeof sig.signatureIdentity!=='string'||sig.signatureType!=='ES256K'||typeof sig.signatureValue!=='string'||sig.signatureIdentity.toLowerCase()!==endpoint.signerIdentity) throw new Error('Missing provenance'); const latestHeight=safeHeight(latest.number); if(safeHeight(sig.blockNumber)!==latestHeight||String(sig.blockHash).toLowerCase()!==latest.hash.toLowerCase()) throw new Error('Signature anchor mismatch'); if(typeof sig.merkleRoot!=='string'||!verifyBlockSignature({identity:sig.signatureIdentity,signatureValue:sig.signatureValue,merkleRoot:sig.merkleRoot})) throw new Error('Signature verification failed'); rows=[...new Map(rows.map(x=>[x.address.toLowerCase(),x])).values()].sort((a,b)=>b.blockNumber-a.blockNumber||a.txHash.localeCompare(b.txHash)); const normalized={latestHeight,latestHash:latest.hash.toLowerCase(),merkleRoot:sig.merkleRoot.toLowerCase(),indexedStartHeight:safeHeight(oldest.number),truncated,rows}; return {...normalized,contracts:rows,latestTime:latest.timestamp,signerIdentity:sig.signatureIdentity.toLowerCase(),digest:createHash('sha256').update(JSON.stringify(normalized)).digest('hex')} }
// Anchor the indexer's reported deployments to the trusted EVM RPC by receipt.
// We can't compare block hashes: cosmos/evm sets the EVM block hash to the
// CometBFT hash, while an ETH-style indexer computes its own header hash, so the
// two never agree. Verifying each returned deployment against its on-chain
// receipt (creation, success, sender, resulting address) is a stronger tamper
// check anyway — it validates the actual inventory rows, not a tangential hash.
async function rpcAnchor(contracts:DeployedContract[],latestHeight:number,wallet:Address){ const rpc=chainDefinition.rpcUrls.default.http[0]; const call=async(method:string,params:unknown[]=[])=>{const r=await fetch(rpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),cache:'no-store'});const b=await r.json() as {result?:unknown;error?:unknown};if(!r.ok||b.error)throw new Error('RPC anchor unavailable');return b.result}; const id=Number(BigInt(String(await call('eth_chainId'))));if(id!==chainDefinition.id)throw new InventoryUnavailableError('RPC chain mismatch'); const head=Number(BigInt(String(await call('eth_blockNumber'))));if(latestHeight>head)throw new InventoryUnavailableError('Indexer ahead of chain head'); for(const c of contracts){ const receipt=await call('eth_getTransactionReceipt',[c.txHash]) as {status?:string;from?:string;to?:string|null;contractAddress?:string|null;blockNumber?:string}|null; if(!receipt)throw new InventoryUnavailableError('Deployment not found on RPC'); if(receipt.status!=='0x1')throw new InventoryUnavailableError('Deployment reverted on RPC'); if(receipt.to!==null)throw new InventoryUnavailableError('Anchored tx is not a contract creation'); if(typeof receipt.from!=='string'||receipt.from.toLowerCase()!==wallet.toLowerCase())throw new InventoryUnavailableError('Deployment sender mismatch'); if(typeof receipt.contractAddress!=='string'||receipt.contractAddress.toLowerCase()!==c.address.toLowerCase())throw new InventoryUnavailableError('Contract address mismatch'); if(safeHeight(receipt.blockNumber)!==c.blockNumber)throw new InventoryUnavailableError('Deployment block mismatch') } }
export async function listDeployedContracts(walletInput:string):Promise<ContractInventory>{ const wallet=getAddress(walletInput);const p=prefix();const configuredEndpoints=endpoints();const settled=await Promise.allSettled(configuredEndpoints.map(endpoint=>source(endpoint,wallet,p)));const registered=new Map(policy.indexers.map(x=>[x.identity.toLowerCase(),x.id]));const unique=new Map<string,Source>();for(const r of settled)if(r.status==='fulfilled'&&registered.has(r.value.signerIdentity))unique.set(r.value.signerIdentity,r.value);const groups=new Map<string,Source[]>();for(const value of unique.values())groups.set(value.digest,[...(groups.get(value.digest)??[]),value]);const qualifying=[...groups.values()].filter(g=>g.length>=policy.agreement.requiredSignerCount);if(qualifying.length!==1)throw new InventoryUnavailableError('No trusted indexer quorum');const agreed=qualifying[0][0];await rpcAnchor(agreed.contracts,agreed.latestHeight,wallet);return {contracts:agreed.contracts,identity:{wallet,chainId:chainDefinition.id},provenance:{source:'Shinzo',signerIds:qualifying[0].map(x=>registered.get(x.signerIdentity)!),requiredSigners:policy.agreement.requiredSignerCount,latestHeight:agreed.latestHeight,latestHash:agreed.latestHash,latestTime:agreed.latestTime,indexedStartHeight:agreed.indexedStartHeight,rpcAgreement:true,collectionPrefix:p},coverage:{complete:!agreed.truncated&&agreed.indexedStartHeight===0,indexedRangeComplete:!agreed.truncated,truncated:agreed.truncated,...(agreed.truncated?{reason:`Inventory capped at ${PAGE_SIZE*MAX_PAGES} successful deployments`}:agreed.indexedStartHeight>0?{reason:`Complete only within indexed range starting at height ${agreed.indexedStartHeight}`}:{})},limitations:{topLevelCreate:true,internalCreate:false,create2:false,ownershipNotEstablished:true}} }
