// src/lib/native-wallet/penumbra/services/ephemeral-address-registry.ts
/**
 * Admin ephemeral address registry service.
 *
 * Generates fresh ephemeral Penumbra addresses, persists registry records,
 * and provides lookup / export / import helpers.
 */

import {
  type CreateEphemeralAddressRecordInput,
  type EphemeralAddressRecord,
  type EphemeralAddressRegistryExport,
  createEphemeralAddressRecord,
  exportEphemeralAddressRegistry,
  parseEphemeralAddressRegistryExport,
} from '@bankd/shared/penumbra'

import {
  findEphemeralAddressRecordsByIntermediateHex,
  findEphemeralAddressRecordsByPenumbraAddress,
  getAllEphemeralAddressRecords,
  saveEphemeralAddressRecord,
  saveEphemeralAddressRecords,
} from '../../core'
import { getPenumbraEphemeralAddressInfo,getWalletIdString } from '../keys'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type GenerateEphemeralAddressInput = Omit<
  CreateEphemeralAddressRecordInput,
  'penumbraAddress' | 'walletId'
>

/** Generate and persist a fresh ephemeral receiving address. */
export async function generateAndSaveEphemeralAddressRecord(
  input: GenerateEphemeralAddressInput,
): Promise<EphemeralAddressRecord> {
  const addressInfo = await getPenumbraEphemeralAddressInfo(input.accountIndex)
  const record = createEphemeralAddressRecord({
    ...input,
    walletId: getWalletIdString(),
    penumbraAddress: addressInfo.bech32,
  })
  await saveEphemeralAddressRecord(record)
  return record
}

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/**
 * Check whether a Penumbra bech32 address belongs to this wallet's ephemeral
 * registry (i.e. was generated by us for external use).
 */
export async function isOwnExternalPenumbraAddress(
  address: string,
): Promise<boolean> {
  const records = await findEphemeralAddressRecordsByPenumbraAddress(address)
  return records.length > 0
}

/**
 * Find all registry records whose derived intermediate (EVM) address matches
 * the given hex address.
 */
export async function findOwnIntermediateRecords(
  address: string,
): Promise<EphemeralAddressRecord[]> {
  return findEphemeralAddressRecordsByIntermediateHex(address)
}

// ---------------------------------------------------------------------------
// Export / Import
// ---------------------------------------------------------------------------

/**
 * Export the full admin ephemeral address registry.
 */
export async function exportAdminEphemeralAddressRegistry(): Promise<EphemeralAddressRegistryExport> {
  const records = await getAllEphemeralAddressRecords()
  return exportEphemeralAddressRegistry(records, getWalletIdString())
}

/**
 * Import an ephemeral address registry export, merging into the local DB.
 */
export async function importAdminEphemeralAddressRegistry(
  value: unknown,
): Promise<void> {
  const parsed = parseEphemeralAddressRegistryExport(value)
  await saveEphemeralAddressRecords(parsed.records)
}
