name: Specs

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "Cargo.lock"
      - "**/Cargo.toml"
      - "tips/verify/**"
      - "crates/alloy/**"
      - "crates/chainspec/**"
      - "crates/contracts/**"
      - "crates/dkg-onchain-artifacts/**"
      - "crates/evm/**"
      - "crates/hardfork/**"
      - "crates/precompiles/**"
      - "crates/precompiles-macros/**"
      - "crates/primitives/**"
      - "crates/revm/**"
      - "scripts/foundry-patch.sh"
      - ".github/workflows/specs.yml"
  pull_request:
    paths:
      - "Cargo.lock"
      - "**/Cargo.toml"
      - "tips/verify/**"
      - "crates/alloy/**"
      - "crates/chainspec/**"
      - "crates/contracts/**"
      - "crates/dkg-onchain-artifacts/**"
      - "crates/evm/**"
      - "crates/hardfork/**"
      - "crates/precompiles/**"
      - "crates/precompiles-macros/**"
      - "crates/primitives/**"
      - "crates/revm/**"
      - "scripts/foundry-patch.sh"
      - ".github/workflows/specs.yml"
  merge_group:

env:
  CARGO_HTTP_TIMEOUT: "180"
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: "true"

jobs:
  specs:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Init submodules
        run: git submodule update --init --depth 1 --recursive shieldd tips/verify/lib
        env:
          GIT_LFS_SKIP_SMUDGE: "1"
      - name: Install toolchain
        run: rustup show active-toolchain || rustup toolchain install
      - uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
        with:
          version: v0.15.0
      - uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1
        with:
          version: nightly
      - parallel:
          - name: Forge fmt
            working-directory: tips/verify
            run: forge fmt --check
          - name: Forge build
            working-directory: tips/verify
            run: forge build --sizes
      - name: Build tempo-std interfaces
        working-directory: tips/verify/lib/tempo-std
        run: forge build --sizes
      - name: ABI alignment check
        run: cargo run -p tempo-xtask -- check-abi
